version: "3"

services:
  hark-test:
    build: .
    network_mode: host
    ipc: host
    tty: true
    volumes:
      - ./workspace:/root/workspace
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities:
              - gpu
